# Generated by Django 5.0.6 on 2024-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=122, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
