# Generated by Django 5.0.6 on 2024-05-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
